application: base-webapp2-jinja2
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- appstats: on
- remote_api: on

libraries:
- name: jinja2
  version: latest

inbound_services:
- warmup

error_handlers:
- file: templates/error_handlers/static/default_error.html
- error_code: over_quota
  file: templates/error_handlers/static/over_quota.html
- error_code: dos_api_denial
  file: templates/error_handlers/static/dos_api_denial.html
- error_code: timeout
  file: templates/error_handlers/static/timeout.html

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.\txt

- url: /static
  static_dir: static

# vurl'd urls - use {% "/static/your/url/here"|vurl %}, and set STATIC_VERSION_NUMBER in app/setting.py
- url: /__v[0-9]+/static/(.*)
  static_files: static/\1
  upload: XXX
  expiration: 365d


- url: /fantasm/.*
  script: fantasm.main.APP
  login: admin

- url: /_cron/.*
  script: main.APP
  login: admin

- url: /dscache/.*
  script: dscache.main.APP
  login: admin

- url: /superadmin/.*
  script: main.APP
  login: admin

- url: /_ah/warmup
  script: warmup.py

- url: .*
  script: main.APP

skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?.*\.bak$
  - ^(.*/)?static/sass